### ISSUE TITLE
Add action param of react-select to onChange method

### ISSUE THREAD

**Issue by j3ernhard** [environment-agency-austria/react-ocean-forms-bootstrap#38]
The onChange method of react-select components has a second parameter which indicates the type of the action.
Add this parameter to the method an provide handleChange as public interface.
[React-Select API](https://react-select.com/props#select-props)

**Comment by maschino** [comment]
@j3ernhard - is this issue still open? If not please close it :) 

You can add `Fixes #38` to your PR description - this will automatically close that issue when you merge the PR.
https://help.github.com/articles/closing-issues-using-keywords/

**Comment by j3ernhard** [comment]
@maschino - this issue is fixed and I will close it.
