### ISSUE TITLE
Reset DatePicker to empty value

### ISSUE THREAD

**Issue by christophka** [environment-agency-austria/react-ocean-forms-bootstrap#55]
I guess that there is a problem with resetting the date picked by a datepicker to an empty value. My use case is a filter view where I can specifiy an date to filter. If I no longer want to use the date as a filter, i have no way of reseting. 
My guess is, that it corresponds with this code:
https://github.com/environment-agency-austria/react-ocean-forms-bootstrap/blob/2b30d3629c0bba4424624a1e88d15dd52b6a64e5/src/components/DatePicker/DatePicker.tsx#L25

Somehow this also leads to a strange bug where you can clear the value and click into another input element. Once you leave that input element or write something into it, the formerly removed value is back for the datepicker

**Comment by maschino** [comment]
@christophka you're right. It seems that the DatePicker does not trigger an onChange event when the value is cleared. The internal state of the form is still holding the old value and when a re-render is triggered the DatePicker gets its old value back. I'll take a look!
